// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package flat

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

/// Packet containing a InterfaceMessage
type InterfacePacketT struct {
	Message *InterfaceMessageT `json:"message"`
}

func (t *InterfacePacketT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil {
		return 0
	}
	messageOffset := t.Message.Pack(builder)

	InterfacePacketStart(builder)
	if t.Message != nil {
		InterfacePacketAddMessageType(builder, t.Message.Type)
	}
	InterfacePacketAddMessage(builder, messageOffset)
	return InterfacePacketEnd(builder)
}

func (rcv *InterfacePacket) UnPackTo(t *InterfacePacketT) {
	messageTable := flatbuffers.Table{}
	if rcv.Message(&messageTable) {
		t.Message = rcv.MessageType().UnPack(messageTable)
	}
}

func (rcv *InterfacePacket) UnPack() *InterfacePacketT {
	if rcv == nil {
		return nil
	}
	t := &InterfacePacketT{}
	rcv.UnPackTo(t)
	return t
}

type InterfacePacket struct {
	_tab flatbuffers.Table
}

func GetRootAsInterfacePacket(buf []byte, offset flatbuffers.UOffsetT) *InterfacePacket {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &InterfacePacket{}
	x.Init(buf, n+offset)
	return x
}

func FinishInterfacePacketBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsInterfacePacket(buf []byte, offset flatbuffers.UOffsetT) *InterfacePacket {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &InterfacePacket{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedInterfacePacketBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *InterfacePacket) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *InterfacePacket) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *InterfacePacket) MessageType() InterfaceMessage {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return InterfaceMessage(rcv._tab.GetByte(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *InterfacePacket) MutateMessageType(n InterfaceMessage) bool {
	return rcv._tab.MutateByteSlot(4, byte(n))
}

func (rcv *InterfacePacket) Message(obj *flatbuffers.Table) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		rcv._tab.Union(obj, o)
		return true
	}
	return false
}

func InterfacePacketStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func InterfacePacketAddMessageType(builder *flatbuffers.Builder, messageType InterfaceMessage) {
	builder.PrependByteSlot(0, byte(messageType), 0)
}
func InterfacePacketAddMessage(builder *flatbuffers.Builder, message flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(message), 0)
}
func InterfacePacketEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
