// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package flat

import "strconv"

type ScoringRule byte

const (
	ScoringRuleDefault            ScoringRule = 0
	ScoringRuleDisableGoalScoring ScoringRule = 1
)

var EnumNamesScoringRule = map[ScoringRule]string{
	ScoringRuleDefault:            "Default",
	ScoringRuleDisableGoalScoring: "DisableGoalScoring",
}

var EnumValuesScoringRule = map[string]ScoringRule{
	"Default":            ScoringRuleDefault,
	"DisableGoalScoring": ScoringRuleDisableGoalScoring,
}

func (v ScoringRule) String() string {
	if s, ok := EnumNamesScoringRule[v]; ok {
		return s
	}
	return "ScoringRule(" + strconv.FormatInt(int64(v), 10) + ")"
}
