// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package flat

import "strconv"

type DebugRendering byte

const (
	/// Renders are ignored unless explicitly enabled per-agent
	DebugRenderingOffByDefault DebugRendering = 0
	/// Rendering is enabled for everyone by default
	DebugRenderingOnByDefault  DebugRendering = 1
	/// Ignore all render attempts at all times
	DebugRenderingAlwaysOff    DebugRendering = 2
)

var EnumNamesDebugRendering = map[DebugRendering]string{
	DebugRenderingOffByDefault: "OffByDefault",
	DebugRenderingOnByDefault:  "OnByDefault",
	DebugRenderingAlwaysOff:    "AlwaysOff",
}

var EnumValuesDebugRendering = map[string]DebugRendering{
	"OffByDefault": DebugRenderingOffByDefault,
	"OnByDefault":  DebugRenderingOnByDefault,
	"AlwaysOff":    DebugRenderingAlwaysOff,
}

func (v DebugRendering) String() string {
	if s, ok := EnumNamesDebugRendering[v]; ok {
		return s
	}
	return "DebugRendering(" + strconv.FormatInt(int64(v), 10) + ")"
}
