// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package flat

import "strconv"

type BoostRestritionMutator byte

const (
	BoostRestritionMutatorDefault    BoostRestritionMutator = 0
	BoostRestritionMutatorAerialOnly BoostRestritionMutator = 1
)

var EnumNamesBoostRestritionMutator = map[BoostRestritionMutator]string{
	BoostRestritionMutatorDefault:    "Default",
	BoostRestritionMutatorAerialOnly: "AerialOnly",
}

var EnumValuesBoostRestritionMutator = map[string]BoostRestritionMutator{
	"Default":    BoostRestritionMutatorDefault,
	"AerialOnly": BoostRestritionMutatorAerialOnly,
}

func (v BoostRestritionMutator) String() string {
	if s, ok := EnumNamesBoostRestritionMutator[v]; ok {
		return s
	}
	return "BoostRestritionMutator(" + strconv.FormatInt(int64(v), 10) + ")"
}
