// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package flat

import "strconv"

type KeepUpRulesMutator byte

const (
	KeepUpRulesMutatorOff              KeepUpRulesMutator = 0
	KeepUpRulesMutatorEnabledIncrement KeepUpRulesMutator = 1
	KeepUpRulesMutatorEnabled          KeepUpRulesMutator = 2
)

var EnumNamesKeepUpRulesMutator = map[KeepUpRulesMutator]string{
	KeepUpRulesMutatorOff:              "Off",
	KeepUpRulesMutatorEnabledIncrement: "EnabledIncrement",
	KeepUpRulesMutatorEnabled:          "Enabled",
}

var EnumValuesKeepUpRulesMutator = map[string]KeepUpRulesMutator{
	"Off":              KeepUpRulesMutatorOff,
	"EnabledIncrement": KeepUpRulesMutatorEnabledIncrement,
	"Enabled":          KeepUpRulesMutatorEnabled,
}

func (v KeepUpRulesMutator) String() string {
	if s, ok := EnumNamesKeepUpRulesMutator[v]; ok {
		return s
	}
	return "KeepUpRulesMutator(" + strconv.FormatInt(int64(v), 10) + ")"
}
