// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package flat

import "strconv"

/// All the different Rumble items
type RumbleItem byte

const (
	/// Kicks an opponent’s car backward
	RumbleItemBoot          RumbleItem = 0
	/// Forces an opponent to boost uncontrollably at supersonic speeds
	RumbleItemDisruptor     RumbleItem = 1
	/// Halts the ball’s movement temporarily
	RumbleItemFreezer       RumbleItem = 2
	/// Punches the ball with significant force
	RumbleItemHaymaker      RumbleItem = 3
	/// Attracts the ball toward your car
	RumbleItemMagnetizer    RumbleItem = 4
	/// Grabs the ball with a cord and pulls it toward you
	RumbleItemPlunger       RumbleItem = 5
	/// Attaches the ball to your car upon impact
	RumbleItemSpike         RumbleItem = 6
	/// Swaps your position and momentum with an opponent
	RumbleItemSwapper       RumbleItem = 7
	/// Creates a funnel cloud that lifts the ball and nearby cars
	RumbleItemTornado       RumbleItem = 8
	/// Pulls your car toward the ball
	RumbleItemGrapplingHook RumbleItem = 9
	/// Allows you to demolish opponents on contact and hit the ball harder
	RumbleItemPowerHitter   RumbleItem = 10
)

var EnumNamesRumbleItem = map[RumbleItem]string{
	RumbleItemBoot:          "Boot",
	RumbleItemDisruptor:     "Disruptor",
	RumbleItemFreezer:       "Freezer",
	RumbleItemHaymaker:      "Haymaker",
	RumbleItemMagnetizer:    "Magnetizer",
	RumbleItemPlunger:       "Plunger",
	RumbleItemSpike:         "Spike",
	RumbleItemSwapper:       "Swapper",
	RumbleItemTornado:       "Tornado",
	RumbleItemGrapplingHook: "GrapplingHook",
	RumbleItemPowerHitter:   "PowerHitter",
}

var EnumValuesRumbleItem = map[string]RumbleItem{
	"Boot":          RumbleItemBoot,
	"Disruptor":     RumbleItemDisruptor,
	"Freezer":       RumbleItemFreezer,
	"Haymaker":      RumbleItemHaymaker,
	"Magnetizer":    RumbleItemMagnetizer,
	"Plunger":       RumbleItemPlunger,
	"Spike":         RumbleItemSpike,
	"Swapper":       RumbleItemSwapper,
	"Tornado":       RumbleItemTornado,
	"GrapplingHook": RumbleItemGrapplingHook,
	"PowerHitter":   RumbleItemPowerHitter,
}

func (v RumbleItem) String() string {
	if s, ok := EnumNamesRumbleItem[v]; ok {
		return s
	}
	return "RumbleItem(" + strconv.FormatInt(int64(v), 10) + ")"
}
