// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package flat

import "strconv"

type LockedDamagePhaseMutator byte

const (
	LockedDamagePhaseMutatorDefault LockedDamagePhaseMutator = 0
	LockedDamagePhaseMutatorHigh    LockedDamagePhaseMutator = 1
)

var EnumNamesLockedDamagePhaseMutator = map[LockedDamagePhaseMutator]string{
	LockedDamagePhaseMutatorDefault: "Default",
	LockedDamagePhaseMutatorHigh:    "High",
}

var EnumValuesLockedDamagePhaseMutator = map[string]LockedDamagePhaseMutator{
	"Default": LockedDamagePhaseMutatorDefault,
	"High":    LockedDamagePhaseMutatorHigh,
}

func (v LockedDamagePhaseMutator) String() string {
	if s, ok := EnumNamesLockedDamagePhaseMutator[v]; ok {
		return s
	}
	return "LockedDamagePhaseMutator(" + strconv.FormatInt(int64(v), 10) + ")"
}
