// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package flat

import "strconv"

type SpawnDemoballMutator byte

const (
	SpawnDemoballMutatorOff SpawnDemoballMutator = 0
	SpawnDemoballMutatorOn  SpawnDemoballMutator = 1
)

var EnumNamesSpawnDemoballMutator = map[SpawnDemoballMutator]string{
	SpawnDemoballMutatorOff: "Off",
	SpawnDemoballMutatorOn:  "On",
}

var EnumValuesSpawnDemoballMutator = map[string]SpawnDemoballMutator{
	"Off": SpawnDemoballMutatorOff,
	"On":  SpawnDemoballMutatorOn,
}

func (v SpawnDemoballMutator) String() string {
	if s, ok := EnumNamesSpawnDemoballMutator[v]; ok {
		return s
	}
	return "SpawnDemoballMutator(" + strconv.FormatInt(int64(v), 10) + ")"
}
