// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package flat

import (
	"bytes"
	flatbuffers "github.com/google/flatbuffers/go"
)

/// A user-defined environment variable to pass to an agent process.
type EnvironmentVariableT struct {
	Name string `json:"name"`
	Value string `json:"value"`
}

func (t *EnvironmentVariableT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil {
		return 0
	}
	nameOffset := flatbuffers.UOffsetT(0)
	if t.Name != "" {
		nameOffset = builder.CreateString(t.Name)
	}
	valueOffset := flatbuffers.UOffsetT(0)
	if t.Value != "" {
		valueOffset = builder.CreateString(t.Value)
	}
	EnvironmentVariableStart(builder)
	EnvironmentVariableAddName(builder, nameOffset)
	EnvironmentVariableAddValue(builder, valueOffset)
	return EnvironmentVariableEnd(builder)
}

func (rcv *EnvironmentVariable) UnPackTo(t *EnvironmentVariableT) {
	t.Name = string(rcv.Name())
	t.Value = string(rcv.Value())
}

func (rcv *EnvironmentVariable) UnPack() *EnvironmentVariableT {
	if rcv == nil {
		return nil
	}
	t := &EnvironmentVariableT{}
	rcv.UnPackTo(t)
	return t
}

type EnvironmentVariable struct {
	_tab flatbuffers.Table
}

func GetRootAsEnvironmentVariable(buf []byte, offset flatbuffers.UOffsetT) *EnvironmentVariable {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &EnvironmentVariable{}
	x.Init(buf, n+offset)
	return x
}

func FinishEnvironmentVariableBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsEnvironmentVariable(buf []byte, offset flatbuffers.UOffsetT) *EnvironmentVariable {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &EnvironmentVariable{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedEnvironmentVariableBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *EnvironmentVariable) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *EnvironmentVariable) Table() flatbuffers.Table {
	return rcv._tab
}

/// Environment variable name.
func (rcv *EnvironmentVariable) Name() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

/// Environment variable name.
func EnvironmentVariableKeyCompare(o1, o2 flatbuffers.UOffsetT, buf []byte) bool {
	obj1 := &EnvironmentVariable{}
	obj2 := &EnvironmentVariable{}
	obj1.Init(buf, flatbuffers.UOffsetT(len(buf))-o1)
	obj2.Init(buf, flatbuffers.UOffsetT(len(buf))-o2)
	return string(obj1.Name()) < string(obj2.Name())
}

func (rcv *EnvironmentVariable) LookupByKey(key string, vectorLocation flatbuffers.UOffsetT, buf []byte) bool {
	span := flatbuffers.GetUOffsetT(buf[vectorLocation-4:])
	start := flatbuffers.UOffsetT(0)
	bKey := []byte(key)
	for span != 0 {
		middle := span / 2
		tableOffset := flatbuffers.GetIndirectOffset(buf, vectorLocation+4*(start+middle))
		obj := &EnvironmentVariable{}
		obj.Init(buf, tableOffset)
		comp := bytes.Compare(obj.Name(), bKey)
		if comp > 0 {
			span = middle
		} else if comp < 0 {
			middle += 1
			start += middle
			span -= middle
		} else {
			rcv.Init(buf, tableOffset)
			return true
		}
	}
	return false
}

/// Environment variable value.
func (rcv *EnvironmentVariable) Value() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

/// Environment variable value.
func EnvironmentVariableStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func EnvironmentVariableAddName(builder *flatbuffers.Builder, name flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(name), 0)
}
func EnvironmentVariableAddValue(builder *flatbuffers.Builder, value flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(value), 0)
}
func EnvironmentVariableEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
