// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package flat

import "strconv"

type TriTipModeMutator byte

const (
	TriTipModeMutatorOff    TriTipModeMutator = 0
	TriTipModeMutatorTritip TriTipModeMutator = 1
)

var EnumNamesTriTipModeMutator = map[TriTipModeMutator]string{
	TriTipModeMutatorOff:    "Off",
	TriTipModeMutatorTritip: "Tritip",
}

var EnumValuesTriTipModeMutator = map[string]TriTipModeMutator{
	"Off":    TriTipModeMutatorOff,
	"Tritip": TriTipModeMutatorTritip,
}

func (v TriTipModeMutator) String() string {
	if s, ok := EnumNamesTriTipModeMutator[v]; ok {
		return s
	}
	return "TriTipModeMutator(" + strconv.FormatInt(int64(v), 10) + ")"
}
