// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package flat

import "strconv"

/// The possible damage levels of a dropshot tile.
type TileDamageLevel byte

const (
	/// The tile has no damage and the ball cannot fall through.
	TileDamageLevelStart   TileDamageLevel = 0
	/// The tile has some damage,
	/// but the ball still cannot fall through.
	TileDamageLevelDamaged TileDamageLevel = 1
	/// The tile has been broken,
	/// and the ball can now fall through.
	TileDamageLevelBroken  TileDamageLevel = 2
)

var EnumNamesTileDamageLevel = map[TileDamageLevel]string{
	TileDamageLevelStart:   "Start",
	TileDamageLevelDamaged: "Damaged",
	TileDamageLevelBroken:  "Broken",
}

var EnumValuesTileDamageLevel = map[string]TileDamageLevel{
	"Start":   TileDamageLevelStart,
	"Damaged": TileDamageLevelDamaged,
	"Broken":  TileDamageLevelBroken,
}

func (v TileDamageLevel) String() string {
	if s, ok := EnumNamesTileDamageLevel[v]; ok {
		return s
	}
	return "TileDamageLevel(" + strconv.FormatInt(int64(v), 10) + ")"
}
