// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package flat

import "strconv"

/// Various game modes.
type GameMode byte

const (
	GameModeSoccar     GameMode = 0
	GameModeHoops      GameMode = 1
	GameModeDropshot   GameMode = 2
	GameModeSnowday    GameMode = 3
	GameModeRumble     GameMode = 4
	GameModeHeatseeker GameMode = 5
	GameModeGridiron   GameMode = 6
	GameModeKnockout   GameMode = 7
)

var EnumNamesGameMode = map[GameMode]string{
	GameModeSoccar:     "Soccar",
	GameModeHoops:      "Hoops",
	GameModeDropshot:   "Dropshot",
	GameModeSnowday:    "Snowday",
	GameModeRumble:     "Rumble",
	GameModeHeatseeker: "Heatseeker",
	GameModeGridiron:   "Gridiron",
	GameModeKnockout:   "Knockout",
}

var EnumValuesGameMode = map[string]GameMode{
	"Soccar":     GameModeSoccar,
	"Hoops":      GameModeHoops,
	"Dropshot":   GameModeDropshot,
	"Snowday":    GameModeSnowday,
	"Rumble":     GameModeRumble,
	"Heatseeker": GameModeHeatseeker,
	"Gridiron":   GameModeGridiron,
	"Knockout":   GameModeKnockout,
}

func (v GameMode) String() string {
	if s, ok := EnumNamesGameMode[v]; ok {
		return s
	}
	return "GameMode(" + strconv.FormatInt(int64(v), 10) + ")"
}
