// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package flat

import "strconv"

type MatchAdminMutator byte

const (
	MatchAdminMutatorOff MatchAdminMutator = 0
	MatchAdminMutatorOn  MatchAdminMutator = 1
)

var EnumNamesMatchAdminMutator = map[MatchAdminMutator]string{
	MatchAdminMutatorOff: "Off",
	MatchAdminMutatorOn:  "On",
}

var EnumValuesMatchAdminMutator = map[string]MatchAdminMutator{
	"Off": MatchAdminMutatorOff,
	"On":  MatchAdminMutatorOn,
}

func (v MatchAdminMutator) String() string {
	if s, ok := EnumNamesMatchAdminMutator[v]; ok {
		return s
	}
	return "MatchAdminMutator(" + strconv.FormatInt(int64(v), 10) + ")"
}
