// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package flat

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type TileT struct {
	Location *Vector3T `json:"location"`
	Team uint32 `json:"team"`
}

func (t *TileT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil {
		return 0
	}
	TileStart(builder)
	locationOffset := t.Location.Pack(builder)
	TileAddLocation(builder, locationOffset)
	TileAddTeam(builder, t.Team)
	return TileEnd(builder)
}

func (rcv *Tile) UnPackTo(t *TileT) {
	t.Location = rcv.Location(nil).UnPack()
	t.Team = rcv.Team()
}

func (rcv *Tile) UnPack() *TileT {
	if rcv == nil {
		return nil
	}
	t := &TileT{}
	rcv.UnPackTo(t)
	return t
}

type Tile struct {
	_tab flatbuffers.Table
}

func GetRootAsTile(buf []byte, offset flatbuffers.UOffsetT) *Tile {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Tile{}
	x.Init(buf, n+offset)
	return x
}

func FinishTileBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsTile(buf []byte, offset flatbuffers.UOffsetT) *Tile {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &Tile{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedTileBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *Tile) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Tile) Table() flatbuffers.Table {
	return rcv._tab
}

/// The location of the tile.
func (rcv *Tile) Location(obj *Vector3) *Vector3 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := o + rcv._tab.Pos
		if obj == nil {
			obj = new(Vector3)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

/// The location of the tile.
/// The team that owns/defends this tile.
func (rcv *Tile) Team() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

/// The team that owns/defends this tile.
func (rcv *Tile) MutateTeam(n uint32) bool {
	return rcv._tab.MutateUint32Slot(6, n)
}

func TileStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func TileAddLocation(builder *flatbuffers.Builder, location flatbuffers.UOffsetT) {
	builder.PrependStructSlot(0, flatbuffers.UOffsetT(location), 0)
}
func TileAddTeam(builder *flatbuffers.Builder, team uint32) {
	builder.PrependUint32Slot(1, team, 0)
}
func TileEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
